# Generated by Django 4.0 on 2021-12-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_description', models.TextField()),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('minimum_bid_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('auction_end_date_time', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
