# Generated by Django 4.0 on 2021-12-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auctionproduct_bidder_delete_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='auction_product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.auctionproduct'),
        ),
    ]
