# Generated by Django 4.0 on 2021-12-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_auctionproduct_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
